---
title: 'BE_REP2'
author: "James Brown"
date: "3/7/2018"
output: html_document
editor_options: 
  chunk_output_type: inline
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Libraries and Reading in Data
````{r}
#############--------------Read in the data-----------------###################
#PC
setwd("/Users/jbrown/Documents/GitHub/Respirometry/Data/")
data=read_excel("Respir.xlsx")
##Remove rows with NA
data=subset(data, VCO2!="NA")

#MAC
#data=read_excel("/Users/JamesB/Google Drive/Graduate School/Self_JamesTBrown/GitHub/Respirometry/Data/Respir.xlsx", sheet = "Sheet1")
##Remove rows with NA
data=subset(data, VCO2!="NA")

#############--------------Preping Data-----------------######################
#Removing "Blank Control" syringes
data=subset(data,data$syringe!="Blank Control")
##Set "syringe" identifier as a character
data$syringe=as.character(data$syringe)
##Set "treat" (read:treatment) as a factor (read:independent variable)
data$treat=as.factor(data$treat)


#############--------df for Larvae Plots and Data Analysis---------#############
dataBE=data
dataBE=subset(dataBE, strain=="BE")
dataBE=subset(dataBE, stage=="L")
par(mfrow=c(1,1))

#############------df for Ten Days Plots and Data Analysis-------#############
data1to10=dataBE
data1to10=subset(data1to10, day==1 | day==2 | day==3 | day==4 | day==6 | day==7 | day==8 | day==9| day==10)
`````

```{r}
####################Selecting Repeated Measures Model##########################
qplot(treat, co2_hourly_mass, data=dataBE, geom="boxplot")
rmod1=lmer(co2_hourly_mass~treat*day+(1|day),data=dataBE) #different intercepts
rmod2=lmer(co2_hourly_mass~treat*day+(1|day)+(1|day/syringe),data=dataBE) #random factor nested within a level
rmod3=lmer(co2_hourly_mass~treat*day+(day|syringe),data=dataBE) #different slopes and intercepts
anova(rmod1,rmod2) #different intercepts vs different slope and intercepts model
anova(rmod1,rmod3) #different intercepts vs nested model
anova(rmod2,rmod3) #nested model vs different slopes and intercepts model
rmoda=lmer(co2_hourly_mass~(1|day),data=dataBE) #model w/o independent var
rmodb=lmer(co2_hourly_mass~treat+(1|day),data=dataBE) # 1 independent var
rmodc=lmer(co2_hourly_mass~treat+day+(1|day),data=dataBE) # 2 independent vars w/o intrx
rmodd=lmer(co2_hourly_mass~treat*day+(1|day),data=dataBE) # 2 independent vars w/ intrx
anova(rmoda,rmodb)#b is better
anova(rmoda,rmodc)#c is better
anova(rmoda,rmodd)#d is better
anova(rmodb,rmodc)#b is better
anova(rmodb,rmodd)#d is better
anova(rmodc,rmodd)#d is better
summary(rmod3) #rmod3 by default/rmodd
````

````{r}
#Comparing the Days
############################Multilevel Model Example##########################

#Pooled scatterplot and linear regression model
tendays=data1to10
gg <- ggplot(tendays, aes(x = day, y = co2_hourly_mass)) +
    geom_smooth(method = "lm", se = FALSE) +
    geom_point(alpha = 0.3, size = 3) +
    theme_bw() + 
    scale_x_continuous(breaks = 0:9)
print(gg)

#Pooled Linear Regression model and prediction, save preditions to df
pooled.model <- lm(co2_hourly_mass ~ day, tendays)
tendays$PooledPredictions=fitted(pooled.model)
summary(pooled.model)

#Plotting the residuals by the fitted model
gg <- qplot(x = fitted(pooled.model), y = resid(pooled.model)) +
    geom_smooth(method = "lm", se = FALSE) +
    geom_point(alpha = 0.3, size = 3) +
    theme_bw()
print(gg)

##Transformation of Pooled linear model and predictions and save 
log.pooled.model <- lm(log(co2_hourly_mass) ~ day, tendays)
tendays$LogPooledPredictions <- exp(fitted(log.pooled.model))
summary(log.pooled.model)

##Plotting transformed residuals for comparison
gg <- qplot(x = fitted(log.pooled.model), y = resid(log.pooled.model)) +
    geom_smooth(method = "lm", se = FALSE) +
    geom_point(alpha = 0.3, size = 3) +
    theme_bw()
print(gg)

##Plotting log values by the original model for comparison
gg <- ggplot(tendays, aes(x = day, y = co2_hourly_mass)) +
    geom_smooth(method = "lm", se = FALSE) +
    geom_line(aes(y = LogPooledPredictions), color = "red") + 
    geom_point(alpha = 0.3, size = 3) +
    theme_bw()

print(gg)

##Plot to look at change in CO2 over time by syringe
gg <- ggplot(tendays, aes(x = day, y = co2_hourly_mass, group = syringe)) +
    geom_smooth(method = "lm", se = FALSE, color = "darkgrey") +
    theme_bw()

print(gg)

##Plotting a line for each larva
gg <- ggplot(tendays, aes(x = day, y = co2_hourly_mass, group = syringe)) +
    geom_smooth(method = "lm", se = FALSE, color = "darkgrey") +
    geom_point(alpha = 0.3, size = 3) +
    facet_wrap(~syringe) +
    theme_bw()

print(gg)

##Plotting regressions specific for each larva to see larva by day interx compared to the pooled data
#Intercept can chage
varying.intercept.model <- lm(co2_hourly_mass ~ day + syringe, tendays)
tendays$VaryingInterceptPredictions <- fitted(varying.intercept.model) #data saver

#Slope can change
varying.slope.model <- lm(co2_hourly_mass ~ day:syringe, tendays)
tendays$VaryingSlopePredictions <- fitted(varying.slope.model)#data saver

#Slope and intercept can change
interaction.model <- lm(co2_hourly_mass ~ day + syringe + day:syringe, tendays)
tendays$InteractionPredictions <- fitted(interaction.model)#data saver

##Plotting each syringe with regression lines for pooled and individual data
gg <- ggplot(tendays, aes(x = day, y = co2_hourly_mass, color=treat)) +
    #geom_line(aes(y = PooledPredictions), color = "darkgrey") +
    #geom_line(aes(y = VaryingInterceptPredictions), color = "blue") +
    #geom_line(aes(y = VaryingSlopePredictions), color = "red") +
    #geom_line(aes(y = InteractionPredictions), color = "black") +
    geom_point(alpha = 0.3, size = 3) +
    theme_bw()

print(gg)

##Regression comparison between multilevel, pooled and unpooled data
ml.model <- lmer(co2_hourly_mass~treat*day+(day|syringe),data=tendays)
# Save the fitted values
tendays$MLPredictions <- fitted(ml.model)

gg <- ggplot(tendays, aes(x = day, y = co2_hourly_mass, group = syringe)) +
    geom_line(aes(y = PooledPredictions), color = "darkgrey") +
    geom_line(aes(y = MLPredictions), color = "red") +
    geom_line(aes(y = InteractionPredictions), color = "black") +
    geom_point(alpha = 0.3, size = 3) +
    theme_bw()

print(gg)

summary(ml.model)
````